In [ ]:
# ! pip install pandas
# ! pip install numpy
# ! pip install matplotlib
# ! pip install seaborn

# ctrl + ? --> put all line of code in the comment

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv(r"D:\Class Laptop\Class Data analysis\Statistics\Csv\sales 1.csv")
data

,index,Date,Year,Month,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Making Cost,Revenue,column_1,column_2,Region_Id
0,0,2/19/2016,2016,February,29,F,United States,Washington,Accessories,Tires and Tubes,1.0,80.00,109.000000,80,109.0,NaN,NaN,101
1,1,2/20/2016,2016,February,29,F,United States,Washington,Clothing,Gloves,2.0,24.50,28.500000,49,57.0,NaN,NaN,103
2,2,2/27/2016,2016,February,29,F,United States,Washington,Accessories,Tires and Tubes,3.0,3.67,5.000000,11,15.0,NaN,NaN,102
3,3,03-12-2016,2016,March,29,F,United States,Washington,Accessories,Tires and Tubes,2.0,87.50,116.500000,175,233.0,NaN,NaN,102
4,4,03-12-2016,2016,March,29,F,United States,Washington,Accessories,Tires and Tubes,3.0,35.00,41.666667,105,125.0,NaN,NaN,102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34878,12,7/22/2016,2016,July,29,F,United States,Washington,Accessories,Tires and Tubes,2.0,46.00,60.000000,92,120.0,NaN,NaN,102
34879,13,7/22/2016,2016,July,29,F,United States,Washington,Accessories,Tires and Tubes,1.0,9.00,10.000000,9,10.0,NaN,NaN,101
34880,14,8/18/2015,2015,August,29,F,United States,Washington,Accessories,Helmets,3.0,151.67,181.333333,455,544.0,NaN,NaN,102
34881,15,8/30/2015,2015,August,29,F,United States,Washington,Accessories,Tires and Tubes,3.0,70.00,72.666667,210,218.0,NaN,NaN,103
34882,16,9/17/2015,2015,September,29,F,United States,Washington,Accessories,Tires and Tubes,1.0,385.00,439.000000,385,439.0,NaN,NaN,103

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 34883 entries, 0 to 34882
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             34883 non-null  int64
 1   Date              34869 non-null  str
 2   Year              34883 non-null  int64
 3   Month             34872 non-null  str
 4   Customer Age      34883 non-null  int64
 5   Customer Gender   34880 non-null  str
 6   Country           34855 non-null  str
 7   State             34873 non-null  str
 8   Product Category  34881 non-null  str
 9   Sub Category      34883 non-null  str
 10  Quantity          34882 non-null  float64
 11  Unit Cost         34879 non-null  float64
 12  Unit Price        34879 non-null  float64
 13  Making Cost       34883 non-null  int64
 14  Revenue           34732 non-null  float64
 15  column_1          0 non-null      float64
 16  column_2          0 non-null      float64
 17  Region_Id         34883 non-null  int64
dtypes: float64(6), int64(5), str(7)
memory usage: 4.8 MB

In [5]:
data.dtypes

index                 int64
Date                    str
Year                  int64
Month                   str
Customer Age          int64
Customer Gender         str
Country                 str
State                   str
Product Category        str
Sub Category            str
Quantity            float64
Unit Cost           float64
Unit Price          float64
Making Cost           int64
Revenue             float64
column_1            float64
column_2            float64
Region_Id             int64
dtype: object

In [6]:
data.columns

Index(['index', 'Date', 'Year', 'Month', 'Customer Age', 'Customer Gender',
       'Country', 'State', 'Product Category', 'Sub Category', 'Quantity',
       'Unit Cost', 'Unit Price', 'Making Cost', 'Revenue', 'column_1',
       'column_2', 'Region_Id'],
      dtype='str')

In [7]:
data.shape

(34883, 18)

In [8]:
data.index

RangeIndex(start=0, stop=34883, step=1)

In [9]:
data.values

array([[0, '2/19/2016', 2016, ..., nan, nan, 101],
       [1, '2/20/2016', 2016, ..., nan, nan, 103],
       [2, '2/27/2016', 2016, ..., nan, nan, 102],
       ...,
       [14, '8/18/2015', 2015, ..., nan, nan, 102],
       [15, '8/30/2015', 2015, ..., nan, nan, 103],
       [16, '9/17/2015', 2015, ..., nan, nan, 103]],
      shape=(34883, 18), dtype=object)

In [11]:
data["Date"]

0         2/19/2016
1         2/20/2016
2         2/27/2016
3        03-12-2016
4        03-12-2016
            ...
34878     7/22/2016
34879     7/22/2016
34880     8/18/2015
34881     8/30/2015
34882     9/17/2015
Name: Date, Length: 34883, dtype: str

In [12]:
data.Date

0         2/19/2016
1         2/20/2016
2         2/27/2016
3        03-12-2016
4        03-12-2016
            ...
34878     7/22/2016
34879     7/22/2016
34880     8/18/2015
34881     8/30/2015
34882     9/17/2015
Name: Date, Length: 34883, dtype: str

In [13]:
data.describe()

,index,Year,Customer Age,Quantity,Unit Cost,Unit Price,Making Cost,Revenue,column_1,column_2,Region_Id
count,34883.000000,34883.000000,34883.000000,34882.000000,34879.000000,34879.000000,34883.000000,34732.000000,0.0,0.0,34883.000000
mean,17424.008285,2015.569360,36.379297,2.002523,349.757223,389.117826,575.780495,640.772199,NaN,NaN,102.491414
std,10069.984721,0.495173,11.111388,0.813925,489.962491,525.259113,690.412137,737.236314,NaN,NaN,1.115591
min,0.000000,2015.000000,17.000000,1.000000,0.670000,0.666667,2.000000,2.000000,NaN,NaN,101.000000
25%,8703.500000,2015.000000,28.000000,1.000000,45.000000,53.666667,85.000000,102.000000,NaN,NaN,101.000000
50%,17424.000000,2016.000000,35.000000,2.000000,150.000000,179.000000,261.000000,317.000000,NaN,NaN,102.000000
75%,26144.500000,2016.000000,44.000000,3.000000,455.000000,521.000000,769.000000,901.000000,NaN,NaN,103.000000
max,34865.000000,2016.000000,87.000000,3.000000,3240.000000,5082.000000,3600.000000,5082.000000,NaN,NaN,104.000000

In [14]:
data.head(1)

,index,Date,Year,Month,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Making Cost,Revenue,column_1,column_2,Region_Id
0,0,2/19/2016,2016,February,29,F,United States,Washington,Accessories,Tires and Tubes,1.0,80.0,109.0,80,109.0,NaN,NaN,101

In [15]:
data.tail(1)

,index,Date,Year,Month,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Making Cost,Revenue,column_1,column_2,Region_Id
34882,16,9/17/2015,2015,September,29,F,United States,Washington,Accessories,Tires and Tubes,1.0,385.0,439.0,385,439.0,NaN,NaN,103

In [16]:
data.shape

(34883, 18)

In [17]:
data.shape[0]

34883

In [18]:
data.shape[1]

18

In [19]:
data.size

627894

In [22]:
data.columns

Index(['index', 'Date', 'Year', 'Month', 'Customer Age', 'Customer Gender',
       'Country', 'State', 'Product Category', 'Sub Category', 'Quantity',
       'Unit Cost', 'Unit Price', 'Making Cost', 'Revenue', 'column_1',
       'column_2', 'Region_Id'],
      dtype='str')

In [21]:
data["Date"]

0         2/19/2016
1         2/20/2016
2         2/27/2016
3        03-12-2016
4        03-12-2016
            ...
34878     7/22/2016
34879     7/22/2016
34880     8/18/2015
34881     8/30/2015
34882     9/17/2015
Name: Date, Length: 34883, dtype: str

In [26]:
data[['Customer Age', "Date", "Region_Id"]]

       Customer Age        Date  Region_Id
0                29   2/19/2016        101
1                29   2/20/2016        103
2                29   2/27/2016        102
3                29  03-12-2016        102
4                29  03-12-2016        102
...             ...         ...        ...
34878            29   7/22/2016        102
34879            29   7/22/2016        101
34880            29   8/18/2015        102
34881            29   8/30/2015        103
34882            29   9/17/2015        103

[34883 rows x 3 columns]

In [23]:
data[['Date', 'Year', 'Month', 'Customer Age']]

             Date  Year      Month  Customer Age
0       2/19/2016  2016   February            29
1       2/20/2016  2016   February            29
2       2/27/2016  2016   February            29
3      03-12-2016  2016      March            29
4      03-12-2016  2016      March            29
...           ...   ...        ...           ...
34878   7/22/2016  2016       July            29
34879   7/22/2016  2016       July            29
34880   8/18/2015  2015     August            29
34881   8/30/2015  2015     August            29
34882   9/17/2015  2015  September            29

[34883 rows x 4 columns]

In [29]:
# loc --> Acp only text info to print data
data.loc[ : ,  'Date'  ]

0         2/19/2016
1         2/20/2016
2         2/27/2016
3        03-12-2016
4        03-12-2016
            ...
34878     7/22/2016
34879     7/22/2016
34880     8/18/2015
34881     8/30/2015
34882     9/17/2015
Name: Date, Length: 34883, dtype: str

In [30]:
data.columns

Index(['index', 'Date', 'Year', 'Month', 'Customer Age', 'Customer Gender',
       'Country', 'State', 'Product Category', 'Sub Category', 'Quantity',
       'Unit Cost', 'Unit Price', 'Making Cost', 'Revenue', 'column_1',
       'column_2', 'Region_Id'],
      dtype='str')

In [ ]:
data.loc[: , 'State' : 'Revenue']

,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Making Cost,Revenue
0,Washington,Accessories,Tires and Tubes,1.0,80.00,109.000000,80,109.0
1,Washington,Clothing,Gloves,2.0,24.50,28.500000,49,57.0
2,Washington,Accessories,Tires and Tubes,3.0,3.67,5.000000,11,15.0
3,Washington,Accessories,Tires and Tubes,2.0,87.50,116.500000,175,233.0
4,Washington,Accessories,Tires and Tubes,3.0,35.00,41.666667,105,125.0
...,...,...,...,...,...,...,...,...
34878,Washington,Accessories,Tires and Tubes,2.0,46.00,60.000000,92,120.0
34879,Washington,Accessories,Tires and Tubes,1.0,9.00,10.000000,9,10.0
34880,Washington,Accessories,Helmets,3.0,151.67,181.333333,455,544.0
34881,Washington,Accessories,Tires and Tubes,3.0,70.00,72.666667,210,218.0
34882,Washington,Accessories,Tires and Tubes,1.0,385.00,439.000000,385,439.0

In [ ]:
data.loc[ : ,  ['Date', 'Year', 'Month', 'Customer Age', 'Customer Gender','Country']  ]

,Date,Year,Month,Customer Age,Customer Gender,Country
0,2/19/2016,2016,February,29,F,United States
1,2/20/2016,2016,February,29,F,United States
2,2/27/2016,2016,February,29,F,United States
3,03-12-2016,2016,March,29,F,United States
4,03-12-2016,2016,March,29,F,United States
...,...,...,...,...,...,...
34878,7/22/2016,2016,July,29,F,United States
34879,7/22/2016,2016,July,29,F,United States
34880,8/18/2015,2015,August,29,F,United States
34881,8/30/2015,2015,August,29,F,United States
34882,9/17/2015,2015,September,29,F,United States

In [32]:
data.loc[ : ,  ['Country', 'Date', 'Month', 'index']  ]

             Country        Date      Month  index
0      United States   2/19/2016   February      0
1      United States   2/20/2016   February      1
2      United States   2/27/2016   February      2
3      United States  03-12-2016      March      3
4      United States  03-12-2016      March      4
...              ...         ...        ...    ...
34878  United States   7/22/2016       July     12
34879  United States   7/22/2016       July     13
34880  United States   8/18/2015     August     14
34881  United States   8/30/2015     August     15
34882  United States   9/17/2015  September     16

[34883 rows x 4 columns]

In [37]:
data.head(0)

Empty DataFrame
Columns: [index, Date, Year, Month, Customer Age, Customer Gender, Country, State, Product Category, Sub Category, Quantity, Unit Cost, Unit Price, Making Cost, Revenue, column_1, column_2, Region_Id]
Index: []

In [40]:
data.iloc[ :, [10,5,1,4,7]]

       Quantity Customer Gender        Date  Customer Age       State
0           1.0               F   2/19/2016            29  Washington
1           2.0               F   2/20/2016            29  Washington
2           3.0               F   2/27/2016            29  Washington
3           2.0               F  03-12-2016            29  Washington
4           3.0               F  03-12-2016            29  Washington
...         ...             ...         ...           ...         ...
34878       2.0               F   7/22/2016            29  Washington
34879       1.0               F   7/22/2016            29  Washington
34880       3.0               F   8/18/2015            29  Washington
34881       3.0               F   8/30/2015            29  Washington
34882       1.0               F   9/17/2015            29  Washington

[34883 rows x 5 columns]

In [39]:
data.iloc[ : , 1:7  ]

,Date,Year,Month,Customer Age,Customer Gender,Country
0,2/19/2016,2016,February,29,F,United States
1,2/20/2016,2016,February,29,F,United States
2,2/27/2016,2016,February,29,F,United States
3,03-12-2016,2016,March,29,F,United States
4,03-12-2016,2016,March,29,F,United States
...,...,...,...,...,...,...
34878,7/22/2016,2016,July,29,F,United States
34879,7/22/2016,2016,July,29,F,United States
34880,8/18/2015,2015,August,29,F,United States
34881,8/30/2015,2015,August,29,F,United States
34882,9/17/2015,2015,September,29,F,United States

In [44]:
data[['Country', 'Date', 'Month', 'index']].head(10).columns

Index(['Country', 'Date', 'Month', 'index'], dtype='str')